services:
    fastapi:
        build: .
        env_file: .env
        expose:
            - 8000
        ports:
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://fastapi:8000/docs"]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 5s
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
    db:
        image: postgres:15.1-alpine
        ports:
            - "5432:5432"
        env_file: .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "homework_db", "-p", "5432", "-h", "db"]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 10s
    redis:
        image: redis/redis-stack
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 3s
    tests:
        build: ./tests
        env_file: .env
        depends_on:
            fastapi:
                condition: service_healthy
